/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sectors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provinces */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List companies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exchanges */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homepage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get homepage */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ops/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get admin operations health snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOpsHealthResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ops/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get admin operations backups snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOpsBackupsResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ops/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get admin operations imports snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOpsImportsResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ops/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get admin operations security snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOpsSecurityResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ops/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get canonical admin operations audit log snapshot */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    category?: "import" | "security" | "ai" | "backup" | "admin-quality" | "governance";
                    severity?: "ready" | "warning" | "offline";
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOpsAuditLogResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ops/ai/proofs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the latest GitHub proof telemetry for each AI provider workflow */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOpsAiProofResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ops/ai/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch a provider-specific GitHub workflow from the owner/admin control plane */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminOpsCodexDispatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOpsCodexDispatchResponse"];
                    };
                };
                /** @description Invalid payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Dispatch disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ops/codex/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compatibility alias for the AI dispatch endpoint */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminOpsCodexDispatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOpsCodexDispatchResponse"];
                    };
                };
                /** @description Invalid payload */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Dispatch disabled */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch statistics summaries */
        get: {
            parameters: {
                query?: {
                    scope?: "interprovincial" | "international" | "all";
                    intrant?: "all" | "energy" | "agriculture" | "manufacturing" | "services";
                    period?: string;
                    province?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatisticsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List billing plans */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["BillingPlan"][];
                            meta?: {
                                count: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feed items */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    sort?: "NEWEST" | "URGENCY" | "VOLUME" | "CREDIBILITY";
                    type?: "OFFER" | "REQUEST" | "ALERT" | "TENDER" | "CAPACITY" | "INDICATOR";
                    mode?: "EXPORT" | "IMPORT" | "BOTH";
                    sector?: string;
                    fromProvince?: string;
                    toProvince?: string;
                    /** @description Exact publication template key stored with feed metadata. */
                    formKey?: string;
                    /** @description Free-text search across title, summary, source label and publication metadata search text. */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedCollectionResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Publish a feed item */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedItemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/feed-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feed actions for the authenticated user */
        get: {
            parameters: {
                query?: {
                    targetType?: components["schemas"]["FeedActionTargetType"];
                    targetId?: string;
                    action?: components["schemas"]["FeedActionType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedActionCollectionResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Record a feed action for the authenticated user */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedActionCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/opportunity-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List opportunity offers for the authenticated user */
        get: {
            parameters: {
                query?: {
                    opportunityId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpportunityOfferCollectionResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Submit an offer for an opportunity */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpportunityOfferCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpportunityOfferResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/opportunity-offer-attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an attachment for an authenticated opportunity offer */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        files: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OpportunityOfferAttachmentResponse"];
                    };
                };
                /** @description Attachment too large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unsupported attachment type */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hydrocarbon-signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List hydrocarbon publication projections */
        get: {
            parameters: {
                query?: {
                    publicationType?: "surplus" | "slowdown";
                    storagePressureLevel?: "low" | "medium" | "high" | "critical";
                    originProvinceId?: string;
                    targetProvinceId?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HydrocarbonSignalCollectionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hydrocarbon-signals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a hydrocarbon signal projection */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HydrocarbonSignalResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation flows */
        get: {
            parameters: {
                query?: {
                    period?: "month" | "quarter" | "year";
                    periodValue?: string;
                    originScope?: "global" | "g7" | "usmca" | "european_union" | "indo_pacific" | "custom";
                    originCodes?: string | string[];
                    hsSections?: string | string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportFlowsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-commodities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation commodities */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCommodityCollections"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-risk-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation risk flags */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportRiskFlag"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation suppliers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportSuppliersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation knowledge */
        get: {
            parameters: {
                query?: {
                    lang?: "fr" | "en";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportKnowledgeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation annotations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportAnnotationsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation watchlists */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportWatchlistsResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create importation watchlist */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportWatchlistCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportWatchlist"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-watchlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update importation watchlist */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportWatchlistUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportWatchlist"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-reports/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule importation report */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportReportScheduleRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportReportScheduleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminOpsHealthResponse: {
            data?: {
                /** Format: date-time */
                generatedAt?: string;
                /** @enum {string} */
                status?: "ok" | "degraded";
                runtime?: {
                    env?: string;
                    nodeVersion?: string;
                    uptimeSeconds?: number;
                };
                memory?: {
                    rssBytes?: number;
                    heapUsedBytes?: number;
                    heapTotalBytes?: number;
                };
                database?: {
                    /** @enum {string} */
                    status?: "ok" | "degraded";
                    users?: number;
                    companies?: number;
                    feedItems?: number;
                };
            };
        };
        AdminOpsBackupsResponse: {
            data?: {
                /** Format: date-time */
                generatedAt?: string;
                /** @enum {string} */
                status?: "ok" | "warning" | "disabled";
                enabled?: boolean;
                directory?: string;
                retentionDays?: number;
                schedule?: string | null;
                totalFiles?: number;
                totalSizeBytes?: number;
                /** Format: date-time */
                lastBackupAt?: string | null;
                files?: {
                    name?: string;
                    sizeBytes?: number;
                    /** Format: date-time */
                    modifiedAt?: string;
                }[];
            };
        };
        AdminOpsImportsResponse: {
            data?: {
                /** Format: date-time */
                generatedAt?: string;
                totalCompanies?: number;
                scannedCompanies?: number;
                truncated?: boolean;
                importedCompanies?: number;
                importsLast24h?: number;
                /** Format: date-time */
                lastImportAt?: string | null;
                sources?: {
                    source?: string;
                    count?: number;
                }[];
                recent?: {
                    id?: string;
                    businessId?: string | null;
                    name?: string;
                    status?: string;
                    source?: string | null;
                    /** Format: date-time */
                    importedAt?: string | null;
                    /** Format: date-time */
                    updatedAt?: string | null;
                }[];
            };
        };
        AdminOpsSecurityResponse: {
            data?: {
                /** Format: date-time */
                generatedAt?: string;
                users?: {
                    total?: number;
                    blocked?: number;
                    registrationsLast7d?: number;
                };
                sessions?: {
                    scannedUsers?: number;
                    truncated?: boolean;
                    active?: number;
                    revoked?: number;
                    usersWithActiveSessions?: number;
                };
                uploads?: {
                    safetyEnabled?: boolean;
                    maxFileSizeBytes?: number;
                    allowedMimeTypes?: string[];
                };
                auth?: {
                    sessionIdleTimeoutMs?: number | null;
                };
                aiKeys?: {
                    /** @enum {string} */
                    provider?: "codex" | "copilot" | "claude" | "gemini";
                    label?: string;
                    workflow?: string;
                    secretName?: string | null;
                    dispatchEnabled?: boolean;
                    keyInserted?: boolean;
                    /** @enum {string} */
                    state?: "ready" | "offline" | "scan-unavailable" | "unsupported";
                    note?: string;
                }[];
                moderation?: {
                    pendingCompanies?: number;
                    suspendedCompanies?: number;
                };
            };
        };
        AdminOpsAuditLogResponse: {
            data?: {
                /** Format: date-time */
                generatedAt?: string;
                /** @enum {string} */
                source?: "admin-ops-audit-log";
                truncated?: boolean;
                entries?: components["schemas"]["AdminOpsAuditLogEntry"][];
            };
        };
        AdminOpsAuditLogEntry: {
            id?: string;
            /** @enum {string} */
            category?: "import" | "security" | "ai" | "backup" | "admin-quality" | "governance";
            action?: string;
            /** @enum {string} */
            eyebrow?: "Import" | "Security" | "AI" | "Backup" | "Admin quality" | "Governance";
            title?: string;
            summary?: string;
            /** Format: date-time */
            occurredAt?: string;
            sourceRoute?: string;
            /** @enum {string} */
            severity?: "ready" | "warning" | "offline";
            actor?: string;
            target?: string;
            metadata?: {
                [key: string]: (string | number | boolean) | null;
            };
        };
        AdminOpsAiProofResponse: {
            data?: {
                /** Format: date-time */
                generatedAt?: string;
                providers?: {
                    /** @enum {string} */
                    provider?: "codex" | "copilot" | "claude" | "gemini";
                    label?: string;
                    workflow?: string;
                    /** @enum {string} */
                    state?: "queued" | "in-progress" | "completed" | "failed" | "unavailable";
                    summary?: string;
                    run?: {
                        id?: number | null;
                        number?: number | null;
                        url?: string | null;
                        displayTitle?: string | null;
                        correlationId?: string | null;
                        status?: string | null;
                        conclusion?: string | null;
                        branch?: string | null;
                        /** Format: date-time */
                        createdAt?: string | null;
                        /** Format: date-time */
                        updatedAt?: string | null;
                    } | null;
                    artifacts?: {
                        id?: number | null;
                        name?: string;
                        sizeBytes?: number;
                        expired?: boolean;
                        url?: string | null;
                    }[];
                    pullRequest?: {
                        number?: number | null;
                        title?: string;
                        url?: string | null;
                        state?: string;
                        merged?: boolean;
                        branch?: string | null;
                    } | null;
                }[];
            };
        };
        AdminOpsCodexDispatchRequest: {
            /** @enum {string} */
            provider?: "codex" | "copilot" | "claude" | "gemini";
            task: string;
            /** @enum {string} */
            scope: "openg7-org" | "strapi" | "packages-contracts" | "packages-tooling" | "repository-root";
            baseBranch: string;
            draftPr: boolean;
            model?: string | null;
            effort?: string | null;
            correlationId?: string | null;
            idempotencyKey?: string | null;
        };
        AdminOpsCodexDispatchResponse: {
            data?: {
                queued?: boolean;
                /** @enum {string} */
                provider?: "github-actions";
                /** @enum {string} */
                selectedProvider?: "codex" | "copilot" | "claude" | "gemini";
                owner?: string;
                repo?: string;
                workflow?: string;
                ref?: string;
                /** Format: date-time */
                requestedAt?: string;
                request?: {
                    /** @enum {string} */
                    selectedProvider?: "codex" | "copilot" | "claude" | "gemini";
                    /** @enum {string} */
                    scope?: "openg7-org" | "strapi" | "packages-contracts" | "packages-tooling" | "repository-root";
                    baseBranch?: string;
                    draftPr?: boolean;
                    model?: string | null;
                    effort?: string | null;
                    correlationId?: string | null;
                    idempotencyKey?: string | null;
                    taskLength?: number;
                };
            };
        };
        Province: {
            id: number;
            name: string;
        };
        Sector: {
            id: number;
            name: string;
        };
        CompanyCapacity: {
            label: string;
            value?: number | null;
            unit?: string | null;
        };
        Company: {
            id: number;
            name: string;
            description?: string | null;
            website?: string | null;
            /** @enum {string} */
            status: "pending" | "approved" | "suspended";
            logoUrl?: string | null;
            secondaryLogoUrl?: string | null;
            capacities?: components["schemas"]["CompanyCapacity"][];
            sector?: components["schemas"]["Sector"];
            province?: components["schemas"]["Province"];
        };
        Exchange: {
            slug: string;
            title: {
                [key: string]: string;
            };
            value: number;
            unit: string;
            sourceProvince: number;
            targetProvince: number;
        };
        FeedPublicationFormMetadata: {
            formKey: string;
            schemaVersion: number;
        };
        FeedPublicationMetadata: {
            publicationForm?: components["schemas"]["FeedPublicationFormMetadata"];
            extensions?: {
                [key: string]: unknown;
            } | null;
        };
        FeedQuantity: {
            value: number;
            /** @enum {string} */
            unit: "MW" | "MWh" | "bbl" | "bbl_d" | "ton" | "kg" | "hours" | "cad" | "usd";
        };
        HydrocarbonSignal: {
            id: string;
            feedItemId: string;
            title: string;
            summary: string;
            companyName: string;
            /** @enum {string} */
            publicationType: "surplus" | "slowdown";
            /** @enum {string} */
            productType: "crudeOil" | "bitumen" | "syntheticCrude" | "diesel" | "other";
            /** @enum {string} */
            businessReason: "surplusStock" | "demandSlowdown" | "transportDisruption" | "buyerOutage" | "priceWindow";
            volumeBarrels: number;
            /** @enum {string} */
            quantityUnit: "bbl" | "bbl_d";
            minimumLotBarrels?: number | null;
            /** Format: date */
            availableFrom?: string | null;
            /** Format: date */
            availableUntil?: string | null;
            estimatedDelayDays?: number | null;
            originProvinceId?: string | null;
            targetProvinceId?: string | null;
            originSite: string;
            /** @enum {string} */
            qualityGrade: "wcs" | "wtiLinked" | "syntheticBlend" | "other";
            logisticsMode: string[];
            targetScope: string[];
            /** @enum {string} */
            storagePressureLevel: "low" | "medium" | "high" | "critical";
            priceReference?: string | null;
            /** Format: date */
            responseDeadline?: string | null;
            contactChannel: string;
            notes?: string | null;
            tags: string[];
            /** @enum {string} */
            sourceKind: "GOV" | "COMPANY" | "PARTNER" | "USER";
            sourceLabel: string;
            /** @enum {string} */
            status: "active" | "expired" | "closed";
        };
        HydrocarbonSignalResponse: {
            data: components["schemas"]["HydrocarbonSignal"];
        };
        HydrocarbonSignalCollectionResponse: {
            data: components["schemas"]["HydrocarbonSignal"][];
            meta: {
                count: number;
                limit: number;
            };
        };
        FeedSource: {
            /** @enum {string} */
            kind: "GOV" | "COMPANY" | "PARTNER" | "USER";
            label: string;
            url?: string | null;
        };
        FeedItem: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string | null;
            /** @enum {string} */
            type: "OFFER" | "REQUEST" | "ALERT" | "TENDER" | "CAPACITY" | "INDICATOR";
            sectorId?: string | null;
            title: string;
            summary: string;
            fromProvinceId?: string | null;
            toProvinceId?: string | null;
            /** @enum {string} */
            mode: "EXPORT" | "IMPORT" | "BOTH";
            quantity?: components["schemas"]["FeedQuantity"];
            tags?: string[];
            metadata?: components["schemas"]["FeedPublicationMetadata"];
            source: components["schemas"]["FeedSource"];
        };
        FeedItemResponse: {
            data: components["schemas"]["FeedItem"];
        };
        FeedCollectionResponse: {
            data: components["schemas"]["FeedItem"][];
            cursor?: string | null;
        };
        FeedCreateRequest: {
            /** @enum {string} */
            type: "OFFER" | "REQUEST" | "ALERT" | "TENDER" | "CAPACITY" | "INDICATOR";
            title: string;
            summary: string;
            sectorId?: string | null;
            fromProvinceId?: string | null;
            toProvinceId?: string | null;
            /** @enum {string} */
            mode: "EXPORT" | "IMPORT" | "BOTH";
            quantity?: components["schemas"]["FeedQuantity"];
            tags?: string[];
            /** @enum {string|null} */
            originType?: "alert" | "opportunity" | "indicator" | null;
            originId?: string | null;
            connectionMatchId?: number | null;
            metadata?: components["schemas"]["FeedPublicationMetadata"];
        };
        /** @enum {string} */
        FeedActionTargetType: "opportunity" | "alert" | "indicator" | "feed-item";
        /** @enum {string} */
        FeedActionType: "save" | "unsave" | "subscribe" | "report-update" | "report-opportunity" | "archive" | "duplicate" | "share" | "create-indicator-alert";
        /** @enum {string} */
        FeedActionStatus: "completed" | "queued" | "failed";
        FeedActionRecord: {
            id: string;
            targetType: components["schemas"]["FeedActionTargetType"];
            targetId: string;
            action: components["schemas"]["FeedActionType"];
            status: components["schemas"]["FeedActionStatus"];
            sourceRoute: string | null;
            targetRoute: string | null;
            metadata: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            createdAt: string | null;
            /** Format: date-time */
            updatedAt: string | null;
            correlationId?: string | null;
            idempotencyKey?: string | null;
        };
        FeedActionCreateRequest: {
            targetType: components["schemas"]["FeedActionTargetType"];
            targetId: string;
            action: components["schemas"]["FeedActionType"];
            status?: components["schemas"]["FeedActionStatus"];
            sourceRoute?: string | null;
            targetRoute?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            occurredAt?: string;
            correlationId?: string | null;
        };
        FeedActionResponse: {
            data: components["schemas"]["FeedActionRecord"];
        };
        FeedActionCollectionResponse: {
            data: components["schemas"]["FeedActionRecord"][];
        };
        OpportunityOfferActivityRecord: {
            id: string;
            /** @enum {string} */
            type: "submitted" | "tracked" | "qualified" | "inDiscussion" | "partiallyServed" | "withdrawn";
            /** @enum {string} */
            actor: "sender" | "system";
            /** Format: date-time */
            createdAt: string;
        };
        OpportunityOfferRecord: {
            id: string;
            reference: string;
            opportunityId: string;
            opportunityTitle: string;
            opportunityRoute?: string | null;
            feedItemId?: string | null;
            /** @enum {string} */
            recipientKind: "GOV" | "COMPANY" | "PARTNER" | "USER";
            recipientLabel: string;
            senderUserId: string;
            senderLabel: string;
            /** Format: email */
            senderEmail: string;
            capacityMw: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            pricingModel: string;
            comment: string;
            attachmentId?: string | null;
            attachmentName?: string | null;
            /** @enum {string} */
            status: "submitted" | "inDiscussion" | "partiallyServed" | "withdrawn";
            allocatedCapacityMw?: number | null;
            remainingOpportunityCapacityMw?: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            withdrawnAt?: string | null;
            activities: components["schemas"]["OpportunityOfferActivityRecord"][];
            correlationId?: string | null;
            idempotencyKey?: string | null;
        };
        OpportunityOfferCreateRequest: {
            opportunityId: string;
            opportunityTitle: string;
            opportunityRoute?: string | null;
            feedItemId?: string | null;
            /** @enum {string} */
            recipientKind: "GOV" | "COMPANY" | "PARTNER" | "USER";
            recipientLabel: string;
            capacityMw: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            pricingModel: string;
            comment: string;
            attachmentId?: string | null;
            attachmentName?: string | null;
            correlationId?: string | null;
        };
        OpportunityOfferAttachmentRecord: {
            id: string;
            name: string;
            /** @enum {string} */
            mime: "application/pdf" | "image/jpeg" | "image/png" | "image/webp";
            size: number;
            url: string | null;
            /** @enum {string} */
            scanStatus: "passed";
        };
        OpportunityOfferAttachmentResponse: {
            data: components["schemas"]["OpportunityOfferAttachmentRecord"];
        };
        OpportunityOfferResponse: {
            data: components["schemas"]["OpportunityOfferRecord"];
        };
        OpportunityOfferCollectionResponse: {
            data: components["schemas"]["OpportunityOfferRecord"][];
        };
        BillingPlanPrice: {
            amount: number;
            currency: string;
            /** @enum {string} */
            interval: "month" | "year";
        };
        BillingPlanCapabilities: {
            premiumVisibility: boolean;
            priorityAnalytics: boolean;
        };
        BillingPlan: {
            id: string;
            /** @enum {string} */
            tier: "free" | "premium";
            /** @enum {string} */
            provider: "internal" | "stripe";
            price: components["schemas"]["BillingPlanPrice"];
            features: string[];
            capabilities: components["schemas"]["BillingPlanCapabilities"];
            i18nKey: string;
            highlight: boolean;
            available: boolean;
        };
        StatisticsSummary: {
            id: number;
            slug?: string | null;
            /** @enum {string} */
            scope: "interprovincial" | "international" | "all";
            /** @enum {string} */
            intrant: "all" | "energy" | "agriculture" | "manufacturing" | "services";
            value?: number | null;
            change?: number | null;
            unitKey?: string | null;
            titleKey: string;
            descriptionKey: string;
            period?: string | null;
            province?: string | null;
        };
        StatisticsInsight: {
            id: number;
            slug?: string | null;
            /** @enum {string} */
            scope: "interprovincial" | "international" | "all";
            /** @enum {string} */
            intrant: "all" | "energy" | "agriculture" | "manufacturing" | "services";
            titleKey: string;
            descriptionKey: string;
            period?: string | null;
            province?: string | null;
        };
        StatisticsSnapshot: {
            totalFlows?: number | null;
            totalFlowsUnitKey?: string | null;
            activeCorridors: number;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        StatisticsResponse: {
            data: {
                summaries: components["schemas"]["StatisticsSummary"][];
                insights: components["schemas"]["StatisticsInsight"][];
                snapshot?: components["schemas"]["StatisticsSnapshot"];
                availablePeriods: string[];
                availableProvinces: string[];
            };
            meta?: {
                filters?: {
                    scope?: string | null;
                    intrant?: string | null;
                    period?: string | null;
                    province?: string | null;
                };
            };
        };
        ImportFlowCorridor: {
            target: string;
            value: number;
            delta?: number | null;
        };
        ImportFlow: {
            originCode: string;
            originName: string;
            value: number;
            yoyDelta?: number | null;
            share?: number | null;
            coordinate?: number[] | null;
            corridors: components["schemas"]["ImportFlowCorridor"][];
        };
        ImportTimelinePoint: {
            period: string;
            label: string;
            totalValue: number;
            yoyDelta?: number | null;
            isProjected?: boolean;
        };
        ImportFlowsResponse: {
            timeline: components["schemas"]["ImportTimelinePoint"][];
            flows: components["schemas"]["ImportFlow"][];
            coverage?: number | null;
            /** Format: date-time */
            lastUpdated?: string | null;
            dataProvider?: string | null;
        };
        ImportCommodity: {
            id: string;
            hsCode: string;
            hsSection: string;
            label: string;
            originCode: string;
            value: number;
            yoyDelta?: number | null;
            riskScore?: number | null;
            sparkline: number[];
            flags: string[];
        };
        ImportCommodityCollections: {
            top: components["schemas"]["ImportCommodity"][];
            emerging: components["schemas"]["ImportCommodity"][];
            risk: components["schemas"]["ImportCommodity"][];
        };
        ImportRiskFlag: {
            id: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high";
            title: string;
            description: string;
            recommendedAction?: string | null;
            relatedCommodityId?: string | null;
        };
        ImportSupplier: {
            id: string;
            name: string;
            dependencyScore?: number | null;
            diversificationScore?: number | null;
            reliability?: number | null;
            country: string;
            originCode: string;
            lastReviewed?: string | null;
            recommendation?: string | null;
        };
        ImportSuppliersResponse: {
            suppliers: components["schemas"]["ImportSupplier"][];
        };
        ImportKnowledgeArticle: {
            id: string;
            title: string;
            summary: string;
            publishedAt: string;
            link: string;
            tag: string;
            thumbnailUrl?: string | null;
        };
        ImportKnowledgeCta: {
            id: string;
            title: string;
            subtitle: string;
            actionLabel: string;
            actionLink: string;
        };
        ImportKnowledgeResponse: {
            articles: components["schemas"]["ImportKnowledgeArticle"][];
            cta?: components["schemas"]["ImportKnowledgeCta"];
        };
        ImportAnnotation: {
            id: string;
            author: string;
            authorAvatarUrl?: string | null;
            excerpt: string;
            /** Format: date-time */
            createdAt: string;
            relatedCommodityId?: string | null;
            relatedOriginCode?: string | null;
        };
        ImportAnnotationsResponse: {
            annotations: components["schemas"]["ImportAnnotation"][];
        };
        ImportFilters: {
            /** @enum {string} */
            periodGranularity: "month" | "quarter" | "year";
            periodValue?: string | null;
            /** @enum {string} */
            originScope: "global" | "g7" | "usmca" | "european_union" | "indo_pacific" | "custom";
            originCodes: string[];
            hsSections: string[];
            compareMode: boolean;
            compareWith?: string | null;
        };
        ImportWatchlist: {
            id: string;
            name: string;
            owner: string;
            /** Format: date-time */
            updatedAt: string;
            filters: components["schemas"]["ImportFilters"];
        };
        ImportWatchlistsResponse: {
            watchlists: components["schemas"]["ImportWatchlist"][];
        };
        ImportWatchlistCreateRequest: {
            name: string;
            filters: components["schemas"]["ImportFilters"];
        };
        ImportWatchlistUpdateRequest: {
            name?: string;
            filters?: components["schemas"]["ImportFilters"];
        };
        ImportReportScheduleRequest: {
            /** @enum {string} */
            period: "month" | "quarter" | "year";
            recipients: string[];
            /** @enum {string} */
            format: "csv" | "json" | "look";
            /** @enum {string} */
            frequency: "weekly" | "monthly" | "quarterly";
            notes?: string | null;
        };
        ImportReportScheduleResponse: {
            scheduled: boolean;
            reportId: string;
            /** Format: date-time */
            scheduledAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
