/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sectors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provinces */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List companies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exchanges */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homepage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get homepage */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch statistics summaries */
        get: {
            parameters: {
                query?: {
                    scope?: "interprovincial" | "international" | "all";
                    intrant?: "all" | "energy" | "agriculture" | "manufacturing" | "services";
                    period?: string;
                    province?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatisticsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List billing plans */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["BillingPlan"][];
                            meta?: {
                                count: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation flows */
        get: {
            parameters: {
                query?: {
                    period?: "month" | "quarter" | "year";
                    periodValue?: string;
                    originScope?: "global" | "g7" | "usmca" | "european_union" | "indo_pacific" | "custom";
                    originCodes?: string | string[];
                    hsSections?: string | string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportFlowsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-commodities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation commodities */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCommodityCollections"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-risk-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation risk flags */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportRiskFlag"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation suppliers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportSuppliersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation knowledge */
        get: {
            parameters: {
                query?: {
                    lang?: "fr" | "en";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportKnowledgeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation annotations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportAnnotationsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch importation watchlists */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportWatchlistsResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create importation watchlist */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportWatchlistCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportWatchlist"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-watchlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update importation watchlist */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportWatchlistUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportWatchlist"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import-reports/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule importation report */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportReportScheduleRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportReportScheduleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Province: {
            id: number;
            name: string;
        };
        Sector: {
            id: number;
            name: string;
        };
        CompanyCapacity: {
            label: string;
            value?: number | null;
            unit?: string | null;
        };
        Company: {
            id: number;
            name: string;
            description?: string | null;
            website?: string | null;
            /** @enum {string} */
            status: "pending" | "approved" | "suspended";
            logoUrl?: string | null;
            secondaryLogoUrl?: string | null;
            capacities?: components["schemas"]["CompanyCapacity"][];
            sector?: components["schemas"]["Sector"];
            province?: components["schemas"]["Province"];
        };
        Exchange: {
            slug: string;
            title: {
                [key: string]: string;
            };
            value: number;
            unit: string;
            sourceProvince: number;
            targetProvince: number;
        };
        BillingPlanPrice: {
            amount: number;
            currency: string;
            /** @enum {string} */
            interval: "month" | "year";
        };
        BillingPlanCapabilities: {
            premiumVisibility: boolean;
            priorityAnalytics: boolean;
        };
        BillingPlan: {
            id: string;
            /** @enum {string} */
            tier: "free" | "premium";
            /** @enum {string} */
            provider: "internal" | "stripe";
            price: components["schemas"]["BillingPlanPrice"];
            features: string[];
            capabilities: components["schemas"]["BillingPlanCapabilities"];
            i18nKey: string;
            highlight: boolean;
            available: boolean;
        };
        StatisticsSummary: {
            id: number;
            slug?: string | null;
            /** @enum {string} */
            scope: "interprovincial" | "international" | "all";
            /** @enum {string} */
            intrant: "all" | "energy" | "agriculture" | "manufacturing" | "services";
            value?: number | null;
            change?: number | null;
            unitKey?: string | null;
            titleKey: string;
            descriptionKey: string;
            period?: string | null;
            province?: string | null;
        };
        StatisticsInsight: {
            id: number;
            slug?: string | null;
            /** @enum {string} */
            scope: "interprovincial" | "international" | "all";
            /** @enum {string} */
            intrant: "all" | "energy" | "agriculture" | "manufacturing" | "services";
            titleKey: string;
            descriptionKey: string;
            period?: string | null;
            province?: string | null;
        };
        StatisticsSnapshot: {
            totalFlows?: number | null;
            totalFlowsUnitKey?: string | null;
            activeCorridors: number;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        StatisticsResponse: {
            data: {
                summaries: components["schemas"]["StatisticsSummary"][];
                insights: components["schemas"]["StatisticsInsight"][];
                snapshot?: components["schemas"]["StatisticsSnapshot"];
                availablePeriods: string[];
                availableProvinces: string[];
            };
            meta?: {
                filters?: {
                    scope?: string | null;
                    intrant?: string | null;
                    period?: string | null;
                    province?: string | null;
                };
            };
        };
        ImportFlowCorridor: {
            target: string;
            value: number;
            delta?: number | null;
        };
        ImportFlow: {
            originCode: string;
            originName: string;
            value: number;
            yoyDelta?: number | null;
            share?: number | null;
            coordinate?: number[] | null;
            corridors: components["schemas"]["ImportFlowCorridor"][];
        };
        ImportTimelinePoint: {
            period: string;
            label: string;
            totalValue: number;
            yoyDelta?: number | null;
            isProjected?: boolean;
        };
        ImportFlowsResponse: {
            timeline: components["schemas"]["ImportTimelinePoint"][];
            flows: components["schemas"]["ImportFlow"][];
            coverage?: number | null;
            /** Format: date-time */
            lastUpdated?: string | null;
            dataProvider?: string | null;
        };
        ImportCommodity: {
            id: string;
            hsCode: string;
            hsSection: string;
            label: string;
            originCode: string;
            value: number;
            yoyDelta?: number | null;
            riskScore?: number | null;
            sparkline: number[];
            flags: string[];
        };
        ImportCommodityCollections: {
            top: components["schemas"]["ImportCommodity"][];
            emerging: components["schemas"]["ImportCommodity"][];
            risk: components["schemas"]["ImportCommodity"][];
        };
        ImportRiskFlag: {
            id: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high";
            title: string;
            description: string;
            recommendedAction?: string | null;
            relatedCommodityId?: string | null;
        };
        ImportSupplier: {
            id: string;
            name: string;
            dependencyScore?: number | null;
            diversificationScore?: number | null;
            reliability?: number | null;
            country: string;
            originCode: string;
            lastReviewed?: string | null;
            recommendation?: string | null;
        };
        ImportSuppliersResponse: {
            suppliers: components["schemas"]["ImportSupplier"][];
        };
        ImportKnowledgeArticle: {
            id: string;
            title: string;
            summary: string;
            publishedAt: string;
            link: string;
            tag: string;
            thumbnailUrl?: string | null;
        };
        ImportKnowledgeCta: {
            id: string;
            title: string;
            subtitle: string;
            actionLabel: string;
            actionLink: string;
        };
        ImportKnowledgeResponse: {
            articles: components["schemas"]["ImportKnowledgeArticle"][];
            cta?: components["schemas"]["ImportKnowledgeCta"];
        };
        ImportAnnotation: {
            id: string;
            author: string;
            authorAvatarUrl?: string | null;
            excerpt: string;
            /** Format: date-time */
            createdAt: string;
            relatedCommodityId?: string | null;
            relatedOriginCode?: string | null;
        };
        ImportAnnotationsResponse: {
            annotations: components["schemas"]["ImportAnnotation"][];
        };
        ImportFilters: {
            /** @enum {string} */
            periodGranularity: "month" | "quarter" | "year";
            periodValue?: string | null;
            /** @enum {string} */
            originScope: "global" | "g7" | "usmca" | "european_union" | "indo_pacific" | "custom";
            originCodes: string[];
            hsSections: string[];
            compareMode: boolean;
            compareWith?: string | null;
        };
        ImportWatchlist: {
            id: string;
            name: string;
            owner: string;
            /** Format: date-time */
            updatedAt: string;
            filters: components["schemas"]["ImportFilters"];
        };
        ImportWatchlistsResponse: {
            watchlists: components["schemas"]["ImportWatchlist"][];
        };
        ImportWatchlistCreateRequest: {
            name: string;
            filters: components["schemas"]["ImportFilters"];
        };
        ImportWatchlistUpdateRequest: {
            name?: string;
            filters?: components["schemas"]["ImportFilters"];
        };
        ImportReportScheduleRequest: {
            /** @enum {string} */
            period: "month" | "quarter" | "year";
            recipients: string[];
            /** @enum {string} */
            format: "csv" | "json" | "look";
            /** @enum {string} */
            frequency: "weekly" | "monthly" | "quarterly";
            notes?: string | null;
        };
        ImportReportScheduleResponse: {
            scheduled: boolean;
            reportId: string;
            /** Format: date-time */
            scheduledAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
